### ISSUE TITLE
Remove the animated Gif's

### ISSUE THREAD

**Issue by wormeyman** [futtta/async-javascript#1]
Hey, @futtta I personally have never liked the animated Gif's in the wizard with the hand punching through the page. Would you accept a pull request if I took them out? I see a few options:

1. Just remove the animated hand Gif's
1. Replace them with static or cleaner looking pictures that are the same size.

Let me know what you think.

**Comment by futtta** [comment]
look at a screenshot of my personal AsyncJS Trello board;

![image](https://user-images.githubusercontent.com/181297/37480246-088b346a-287f-11e8-8b47-aa73edb0c935.png)

I'd be OK with (1), but we'd need to keep the logic of the different blocks somehow. the alternative (replacing them with "cleaner" images) might be needed.
