### ISSUE TITLE
UI cleanup

### ISSUE THREAD

**Issue by wormeyman** [futtta/async-javascript#12]
@futtta  said:

I think the screens need some UI/UX love now that images & whitespace have been removed. esp. the "settings"-tab now is a rather massive screen. There's also some duplication of content on different tabs and the order in "settings" might not make perfect sense either.

**Comment by wormeyman** [comment]
Maybe something like Autoptimize Settings?

**Comment by wormeyman** [comment]
I'm in Seattle area so GMT -7. I'm heading to bed as it is 21:32 as I post this.

**Comment by futtta** [comment]
GMT+1 (DST) here :-)

**Comment by wormeyman** [comment]
The wizard tab is unique because it is run by the javascript so it wasn't as easy to modify as the other tabs where I could just toss out the tables.

**Comment by wormeyman** [comment]
Looking at it now!

**Comment by wormeyman** [comment]
### Sent a PR with more cleanup 😎 

Before we publish we still need to bump the version and update the changelog. Mind if I add myself to the contributors in the `readme.txt`?

**Comment by futtta** [comment]
re. adding to contributors: sure

re. wizard; lots of HTML duplication in there, could we cut back on that
you think? B-)

**Comment by wormeyman** [comment]
I'll take a look tomorrow (for me) I also have been refactoring the JavaScript some more.

**Comment by futtta** [comment]
merged the uicleanup branch @wormeyman , feel free to re-issue your JS PR based on the current state of master.

**Comment by wormeyman** [comment]
👌 Will do!
