### ISSUE TITLE
Swich to WordPress Core UI styled buttons

### ISSUE THREAD

**Issue by wormeyman** [futtta/async-javascript#2]
This will help the buttons match the user's current WordPress color theme `.button` and `.button-primary` are what need to be added. It looks like the buttons are currently unstyled and have a class of `aj_steps_button` which is used by jQuery to load the next step so I'm thinking the final code would look something like `aj_steps_button button`.

Let me know if you would like me to send a pull request.

**Comment by futtta** [comment]
yes please :)
