### ISSUE TITLE
Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in asyncjsDashboardScreens.php

### ISSUE THREAD

**Issue by ettoredn** [futtta/async-javascript#30]
Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in [..]wp-content/plugins/async-javascript/asyncjsDashboardScreens.php on line 14

**Comment by futtta** [comment]
feel free to clone, fix and issue a PR :-)
