### ISSUE TITLE
dashboard widget is broken

### ISSUE THREAD

**Issue by wormeyman** [futtta/async-javascript#5]
only load asyncjs css/ js if on own page https://github.com/futtta/async-javascript/commit/96705be2340beac8aee02c6f8eb78ecb25f032ce ended up breaking the dashboard widget. The dashboard widget now overflows its box and the settings button doesn't work.

**Comment by futtta** [comment]
darn ... so we have to call `aj_enqueue_scripts` from the dashboard page as well. any idea what action to hook into?
