### ISSUE TITLE
css based progress bar?

### ISSUE THREAD

**Issue by wormeyman** [futtta/async-javascript#8]
We have one last image in the plugin that I would like to remove and I'm thinking a CSS loader could work well especially because the current gif is a little blurry on HiDPI displays.

What do you think of: https://codepen.io/wormeyman/pen/RMRjNN

**Comment by futtta** [comment]
Go for it @wormeyman, but maybe make it a tad smaller and sprinkle some love on the "loading" font & position ;-)

**Comment by wormeyman** [comment]
Updated!

Should I swap in `<?php _e('Please Wait','asyncjs'); ?>` so that the loading... text can be translated?

**Comment by futtta** [comment]
Good to go. Good idea to make the text translatable :-)
